---
title: "Day-Ahead Price Prediction"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

library(tidyverse)
library(lubridate)
library(broom)
library(zoo)
library(lubridate)
library(tidymodels)
library(vip)
library(ggforce)

theme_set(theme_bw() +
            theme(plot.title = element_text(face = "bold", size = 14),
                  plot.subtitle = element_text(face = "italic", size = 10,
                                               colour = "grey50")))
```

```{r}
dt <- read_csv("day_ahead.csv")

glimpse(dt)
```

Missing values:

```{r}
colMeans(is.na(dt)) %>% 
  tidy() %>% 
  rename(missing = x) %>% 
  filter(missing > 0) %>% 
  ggplot(aes(missing, 
             names %>% fct_reorder(missing))) +
  geom_col() +
  scale_x_continuous(labels = percent_format())
```

Visualise prices before vs. 2022:

```{r}
dt %>% 
  group_by(day) %>% 
  summarise(price = mean(price, na.rm = T)) %>% 
  ggplot(aes(day, price)) +
  geom_step(size = 0.4) +
  labs(title = "Electricity prices since 2015 until today",
       subtitle = "Horizontal dotted line shows price average before July 2021.\nSource: ENTSO-E Transparency Platform, Day-Ahead Spot Prices",
       y = "EUR/MWh",
       x = NULL) +
  geom_hline(yintercept = mean(dt %>% 
                                 filter(datetime < ymd("2021-07-01")) %>% 
                                 pull(price),
                               na.rm = T),
             lty = "dotted", alpha = 0.5) +
  coord_cartesian(clip="off") +
  expand_limits(y = 0) +
  facet_zoom(x = day >= as.Date("2021-07-01") & day <= as.Date("2023-03-08")) +
  theme(plot.margin = margin(10,30,10,20))

ggsave(units = "cm", width = 20, height = 12, dpi = 350, 
       file = "electricity prices.png")
```

For now, just concerned with price prediction:

```{r}
data <- dt %>% 
  mutate(
    price = lag(price),
    year = year(datetime),
    month = month(datetime),
    day = wday(datetime, week_start = 1),
    hour = hour(datetime),
    month = lubridate::month(datetime),
    year_half = lubridate::semester(datetime) %>% as.factor,
    week_day = lubridate::wday(datetime),
    week_in_year = lubridate::week(datetime),
    quarter = lubridate::quarter(datetime),
    doy = lubridate::yday(datetime),
    dom = lubridate::mday(datetime),
    date_christmas = ifelse(between(doy, 358, 366), 1, 0)
  )

# Include lags up to n
for (i in 25:48){
  var_name <- paste0("price_lag", i)
  data[,var_name] <- lag(data$price, i)
}

data %>% glimpse()
```

```{r}
dt_train <- data %>% 
  filter(year < 2022)

dt_test <- data %>% 
  filter(year == 2022)

rf_rec <- recipe(price ~ ., data = dt_train) %>%
  step_naomit(price) %>% 
  step_date(datetime) %>% 
  step_holiday(datetime, holidays = timeDate::listHolidays("CH")) %>%
  step_impute_mean(all_numeric_predictors())

rf_rec %>% prep() %>% bake(dt_test) %>% glimpse()

cl <- makePSOCKcluster(6)
registerDoParallel(cl)

unregister_dopar <- function() {
  env <- foreach:::.foreachGlobals
  rm(list=ls(name=env), pos=env)
}

rf_fit <- workflow() %>% 
  add_recipe(rf_rec) %>% 
  add_model(rand_forest() %>% 
              set_mode("regression") %>% 
              set_engine("ranger", importance = "permutation")) %>% 
  fit(dt_train)

stopCluster(cl)
unregister_dopar()

rf_fit %>% 
  augment(dt_test) %>% 
  ggplot(aes(price, .pred)) +
  geom_point(alpha = 0.4) +
  geom_abline(colour = "red", lty = "dashed")

eval_metrics <- metric_set(rsq, mae, mape)

rf_fit %>% 
  augment(dt_test) %>% 
  eval_metrics(truth = price, estimate = .pred)

rf_fit %>% 
  augment(dt_test) %>% 
  select(datetime, price, .pred, month) %>% 
  pivot_longer(-c(datetime, month)) %>% 
  ggplot(aes(datetime, value, colour = fct_rev(name))) +
  geom_line(size = 0.5) +
  labs(title = "Forecasts vs. Actuals: Day-Ahead Prices 2022 Switzerland",
       subtitle = "Facetted by month number",
       y = "EUR/MWh",
       x = "Date",
       colour = NULL) +
  facet_wrap(~ month, scales = "free", ncol = 3) +
  scale_y_continuous(labels = comma_format())

write_csv(rf_fit %>% augment(dt_test), "predictions_not_retrained.csv")
```

Variable Importance:

```{r}
rf_fit %>% 
  extract_fit_parsnip() %>% 
  vi() %>% 
  slice_max(Importance, n = 15) %>% 
  ggplot(aes(Importance, 
             Variable %>% fct_reorder(Importance))) +
  geom_col() +
  labs(title = "Variable Importance",
       y = NULL)
```

### Comparing Not-Retrained Model to Retrained Model

Retrain model every week looking back on the past year and predict for the entire next day and then comparing to not retraining throughout 2022.

Random Forest vs. Random Forest:

```{r}
predictions <- read_csv("predictions_not_retrained.csv")
predictions_retrained <- read_csv("predictions_retrained2_rf.csv")

# Pred vs. Actuals
bind_rows(
  predictions_retrained %>% 
    select(.pred, price) %>% 
    mutate(id = "retrained"), 
  predictions %>% 
    select(.pred, price) %>% 
    mutate(id = "not retrained")
) %>%  
  ggplot(aes(price, .pred)) +
  geom_point(alpha = 0.25) +
  geom_abline(colour = "grey50", lty = "dashed") +
  facet_wrap(~ id) +
  labs(title = "Comparing Weekly Retrained Model To Not-Retrained Model",
       x = "Actual EUR/MWh",
       y = "Predicted EUR/MWh")

# Evaluation metrics
eval_metrics <- metric_set(rsq, mae, mape)

bind_rows(
  predictions_retrained %>% 
    select(.pred, price) %>% 
    mutate(id = "retrained"), 
  predictions %>% 
    select(.pred, price) %>% 
    mutate(id = "not retrained")
) %>% 
  group_by(id) %>% 
  eval_metrics(truth = price, estimate = .pred) %>% 
  ggplot(aes(id, .estimate)) +
  geom_col(fill = "midnightblue", alpha = 0.8) +
  facet_wrap(~ .metric, scales = "free_y") +
  labs(title = "Comparing Weekly Retrained Model To Not-Retrained Model",
       y = "Evaluation Metric",
       x = "Model")

# Time Series Plot
bind_rows(
  predictions_retrained %>% 
    select(datetime, price, .pred, month) %>%
    mutate(id = "retrained"), 
  predictions %>% 
    select(datetime, price, .pred, month) %>%
    mutate(id = "not retrained")
) %>% 
  # Look more closely at a shorter period
  # filter(ymd(substr(datetime, 1, 10)) > ymd("2022-01-01"),
  #        ymd(substr(datetime, 1, 10)) < ymd("2022-02-01")) %>% 
  pivot_longer(-c(datetime, id, month)) %>% 
  ggplot(aes(datetime, value, colour = fct_rev(name))) +
  geom_line(size = 0.25, alpha = 0.8) +
  labs(title = "Forecasts vs. Actuals: Day-Ahead Prices 2022 Switzerland",
       y = "EUR/MWh",
       x = "Date",
       colour = NULL) +
  facet_wrap(~ id, scales = "free", ncol = 1) +
  scale_y_continuous(labels = comma_format()) +
  scale_colour_manual(values = c("black", "firebrick")) +
  theme(legend.position = "bottom")

ggsave(units = "cm", width = 25, height = 15, dpi = 350, 
       file = "timeseries plot.pdf")

# Time Series Plot by month
bind_rows(
  predictions_retrained %>% 
    select(datetime, price, .pred, month) %>%
    mutate(id = "retrained"), 
  predictions %>% 
    select(datetime, price, .pred, month) %>%
    mutate(id = "not retrained")
) %>% 
  # Look more closely at a shorter period
  # filter(ymd(substr(datetime, 1, 10)) > ymd("2022-01-01"),
  #        ymd(substr(datetime, 1, 10)) < ymd("2022-02-01")) %>% 
  pivot_longer(-c(datetime, id, month)) %>% 
  ggplot(aes(datetime, value, colour = fct_rev(name))) +
  geom_line(size = 0.5, alpha = 0.8) +
  labs(title = "Forecasts vs. Actuals: Day-Ahead Prices 2022 Switzerland",
       y = "EUR/MWh",
       x = "Date",
       colour = NULL) +
  facet_wrap(month ~ id, scales = "free", ncol = 1) +
  scale_y_continuous(labels = comma_format()) +
  scale_colour_manual(values = c("black", "firebrick")) +
  theme(legend.position = "bottom")

ggsave(width = 8, height = 50, file = "timeseries by month.pdf",
       limitsize = FALSE)

# Deltas by time
bind_rows(
  predictions_retrained %>% 
    select(datetime, price, .pred, month) %>%
    mutate(id = "retrained"), 
  predictions %>% 
    select(datetime, price, .pred, month) %>%
    mutate(id = "not retrained")
) %>% 
  mutate(delta = .pred - price,
         exceedance = if_else(
           abs(delta)/mean(predictions$price, na.rm = T) > 0.1, 
           "outside", "inside"
         )) %>% 
  ggplot(aes(x = datetime, y = delta, 
             colour = exceedance)) +
  geom_point(alpha = 0.25, size = 0.5) +
  facet_wrap(~ id) +
  labs(title = "Residuals") +
  scale_colour_manual(values = c("midnightblue", "firebrick"))
```

Lasso vs. Random Forest:

```{r}
predictions_rf <- read_csv("predictions_retrained2_rf.csv")
predictions_en <- read_csv("predictions_retrained2_lasso.csv")

# Pred vs. Actuals
bind_rows(
  predictions_rf %>% 
    select(.pred, price) %>% 
    mutate(id = "RF"), 
  predictions_en %>% 
    select(.pred, price) %>% 
    mutate(id = "EN")
) %>%  
  ggplot(aes(price, .pred)) +
  geom_point(alpha = 0.25) +
  geom_abline(colour = "grey50", lty = "dashed") +
  facet_wrap(~ id) +
  labs(title = "Comparing Weekly Retrained Model To Not-Retrained Model",
       x = "Actual EUR/MWh",
       y = "Predicted EUR/MWh")

# Evaluation metrics
eval_metrics <- metric_set(rsq, mae, mape)

bind_rows(
  predictions_rf %>% 
    select(.pred, price) %>% 
    mutate(id = "RF"), 
  predictions_en %>% 
    select(.pred, price) %>% 
    mutate(id = "EN")
) %>% 
  group_by(id) %>% 
  eval_metrics(truth = price, estimate = .pred) %>% 
  ggplot(aes(id, .estimate)) +
  geom_col(fill = "midnightblue", alpha = 0.8) +
  facet_wrap(~ .metric, scales = "free_y") +
  labs(title = "Comparing Weekly Retrained Model To Not-Retrained Model",
       y = "Evaluation Metric",
       x = "Model")

# Time Series Plot
bind_rows(
  predictions_rf %>% 
    select(datetime, price, .pred, month) %>%
    mutate(id = "RF"), 
  predictions_en %>% 
    select(datetime, price, .pred, month) %>%
    mutate(id = "EN")
) %>% 
  # Look more closely at a shorter period
  # filter(ymd(substr(datetime, 1, 10)) > ymd("2022-01-01"),
  #        ymd(substr(datetime, 1, 10)) < ymd("2022-02-01")) %>% 
  pivot_longer(-c(datetime, id, month)) %>% 
  ggplot(aes(datetime, value, colour = fct_rev(name))) +
  geom_line(size = 0.25, alpha = 0.8) +
  labs(title = "Forecasts vs. Actuals: Day-Ahead Prices 2022 Switzerland",
       y = "EUR/MWh",
       x = "Date",
       colour = NULL) +
  facet_wrap(~ id, scales = "free", ncol = 1) +
  scale_y_continuous(labels = comma_format()) +
  scale_colour_manual(values = c("black", "firebrick")) +
  theme(legend.position = "bottom")

ggsave(units = "cm", width = 25, height = 15, dpi = 350, 
       file = "timeseries plot.pdf")

# Time Series Plot by month
bind_rows(
  predictions_rf %>% 
    select(datetime, price, .pred, month) %>%
    mutate(id = "RF"), 
  predictions_en %>% 
    select(datetime, price, .pred, month) %>%
    mutate(id = "EN")
) %>% 
  # Look more closely at a shorter period
  # filter(ymd(substr(datetime, 1, 10)) > ymd("2022-01-01"),
  #        ymd(substr(datetime, 1, 10)) < ymd("2022-02-01")) %>% 
  pivot_longer(-c(datetime, id, month)) %>% 
  ggplot(aes(datetime, value, colour = fct_rev(name))) +
  geom_line(size = 0.5, alpha = 0.8) +
  labs(title = "Forecasts vs. Actuals: Day-Ahead Prices 2022 Switzerland",
       y = "EUR/MWh",
       x = "Date",
       colour = NULL) +
  facet_wrap(month ~ id, scales = "free", ncol = 1) +
  scale_y_continuous(labels = comma_format()) +
  scale_colour_manual(values = c("black", "firebrick")) +
  theme(legend.position = "bottom")

ggsave(width = 8, height = 50, file = "timeseries by month RF-EN.pdf",
       limitsize = FALSE)

# Deltas by time
bind_rows(
  predictions_rf %>% 
    select(.pred, price) %>% 
    mutate(id = "RF"), 
  predictions_en %>% 
    select(.pred, price) %>% 
    mutate(id = "EN")
) %>% 
  mutate(delta = .pred - price,
         exceedance = if_else(
           abs(delta)/mean(predictions$price, na.rm = T) > 0.1, 
           "outside", "inside"
         )) %>% 
  ggplot(aes(x = datetime, y = delta, 
             colour = exceedance)) +
  geom_point(alpha = 0.25, size = 0.5) +
  facet_wrap(~ id) +
  labs(title = "Residuals") +
  scale_colour_manual(values = c("midnightblue", "firebrick"))
```
